name: kedro-feature-and-inference-pipelines

on:
  workflow_dispatch:   # Se puede lanzar manualmente desde GitHub Actions

jobs:
  run_kedro_pipelines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Asegura compatibilidad con Kedro y Hopsworks

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip uninstall -y kedro
          pip install -r requirements.txt

      - name: Run Kedro Feature Pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: kedro run --pipeline feature_pipeline

      - name: Run Kedro Inference Pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: kedro run --pipeline inference_pipeline


      - name: Configure Git credentials
        run: |
          git config --global user.name "kedro-actions[bot]"
          git config --global user.email "kedro-actions@example.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/jmeonodstls/kedro-iris-hopsworks.git

      - name: Commit and Push outputs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated pipeline output pushed by GitHub Actions
          file_pattern: |
            data/08_reporting/actual_iris.png
            data/08_reporting/latest_iris.png
            data/08_reporting/confusion_matrix.png
            data/08_reporting/history_predictions.xlsx
          commit_user_name: kedro-actions[bot]
          commit_user_email: kedro-actions@example.com
          branch: main
          repository: .
          commit_author: jmeonodstls <jmeonodstls@users.noreply.github.com>


